model:
  base_learning_rate: 5.0e-03
  target: mvdream.ldm.inv_interface.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 32
    channels: 4
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: mvdream
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    embedding_reg_weight: 0.0
    unfreeze_model: False
    model_lr: 0.0

    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings: ["*"]
        initializer_words: ["object"]
        per_image_tokens: false
        num_vectors_per_token: 32
        progressive_words: false

    unet_config:
      target: mvdream.ldm.modules.diffusionmodules.openaimodel.MultiViewUNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: False
        legacy: False
        camera_dim: 16

    # first_stage_config:
    #   target: ldm.models.autoencoder.AutoencoderKL
    #   params:
    #     embed_dim: 4
    #     monitor: val/rec_loss
    #     ddconfig:
    #       double_z: true
    #       z_channels: 4
    #       resolution: 256
    #       in_channels: 3
    #       out_ch: 3
    #       ch: 128
    #       ch_mult:
    #       - 1
    #       - 2
    #       - 4
    #       - 4
    #       num_res_blocks: 2
    #       attn_resolutions: []
    #       dropout: 0.0
    #     lossconfig:
    #       target: torch.nn.Identity
    first_stage_config:
      target: mvdream.ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.personalized.MVGSPersonalizedBase
      params:
        size: 256
        set: train
        per_image_tokens: false
        repeats: 10
    validation:
      target: ldm.data.personalized.MVGSPersonalizedBase
      params:
        size: 256
        set: val
        per_image_tokens: false
        repeats: 10

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 300
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 6100